---
title: "NEON forecast challenge submission- all sources of  uncertainty"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages, echo = F, warning=F, message=F}
## install.packages('remotes')
## install.packages('fpp3') # package for applying simple forecasting methods
## install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
## install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
## install.packages('lubridate') # working with dates and times
## remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission

# Load packages
library(tidyverse)
library(lubridate)

```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'temperature')
```

```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

variables <- c("air_temperature", "eastward_wind", "northward_wind")
#Other variable names can be found at https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  # convert air temp to C
  mutate(air_temperature = air_temperature - 273.15)

```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(1)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))
variables <- c("air_temperature", "eastward_wind", "northward_wind")

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% variables) |> 
  collect()

noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) |>
  # convert to Celsius
  mutate(air_temperature = air_temperature - 273.15) |> 
  select(datetime, site_id, air_temperature, eastward_wind, northward_wind, parameter)
```

```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  filter(variable == 'temperature') |>
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(noaa_past_mean, 
            by = c("datetime","site_id"))

# Loop through each site to fit the model
temp_lm_forecast <- NULL

```


```{r}
#code ripped from Mary's module 6, set up for including uncertainty
forecast_start_date <- forecast_date


#number of days we are predicting into the future
forecast_horizon <- 7
#vector of dates that we want to predict for
forecasted_dates <- seq(from = ymd(forecast_start_date), to = ymd(forecast_start_date) + forecast_horizon, by = "day")
```


```{r forecast-loop}
forecast_df <- NULL
#for loop to fit a linear regression on every site
for(i in 1:length(lake_sites$field_site_id)) {  
  
  example_site <- lake_sites$field_site_id[i]
  
  #past data to build the lm
  site_target <- targets_lm |>
    filter(site_id == example_site)

  #future data to run on the lm
  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == example_site) %>% 
    filter(datetime <= max(forecasted_dates))
  
  #fitting linear model to past data
  fit <- lm(site_target$temperature ~ site_target$air_temperature + site_target$eastward_wind + site_target$northward_wind)
  fit_sum <- summary(fit)
  fit_sum_df <- as.data.frame(fit_sum$coefficients)
  
  #coeffs <- round(fit$coefficients, 2)
  coeffs <- fit_sum_df[,1]
  params_se <- fit_sum_df[,2]


  #create df containing distribution of parameter uncertainty, done for each new lm for each site
  param_df <- data.frame(b_beta = rnorm(31, coeffs[1], params_se[1]),
                         airT_beta = rnorm(31, coeffs[2], params_se[2]),
                         eWind_beta = rnorm(31, coeffs[3], params_se[3]),
                         nWind_beta = rnorm(31, coeffs[4], params_se[4]))

  #Process uncertainty- uncertainty due to how we model or represent this system
  residuals <- predict(fit, site_target)
  sigma <- sd(residuals, na.rm = TRUE) # Process Uncertainty Noise Std Dev.; this is your sigma
  process_unc <- rnorm(n = 31, mean = 0, sd = sigma)

  # initial condition uncertainty- not included bc I don't have any antecedent conditions
  #ic_sd <- 0.1 
  #ic_uc <- rnorm(n = n_members, mean = curr_wt, sd = ic_sd)

  #run a model run for each ensemble member, incorporating the different sources of uncertainty
  for(x in 1:length(forecasted_dates)) {
    # use linear regression to forecast water temperature for each ensemble member
    #iterating through each day, so filter for day each day individually to predict
    site_drivers <- noaa_future_site %>%
      filter(datetime == forecasted_dates[x]) %>% 
      bind_cols(param_df)
    #defining components of the multi-linear regression- using ones with uncertainty
    b <- site_drivers$b_beta
    airT <- site_drivers$air_temperature * site_drivers$airT_beta
    east <- site_drivers$eastward_wind * site_drivers$eWind_beta
    west <- site_drivers$northward_wind * site_drivers$nWind_beta

    #multi linear regression
    forecasted_temperature <- b + airT + east + west + process_unc
    
    # put all the relevant information into a tibble that we can bind together
    # site_drivers$prediction <- forecasted_temperature
    # if(x == 1) loop2 <- site_drivers
    # if(x > 1) loop2 <- dplyr::bind_rows(loop2, site_drivers)
    
    curr_site_df <- tibble(datetime = rep(forecasted_dates[x], times = 31),
                         site_id = example_site,
                         parameter = 0:30,
                         prediction = forecasted_temperature,
                         variable = "temperature") #Change this if you are forecasting a different variable
  
  forecast_df <- dplyr::bind_rows(forecast_df, curr_site_df)
    

  }
    
  
  
  #temp_lm_forecast <- dplyr::bind_rows(temp_lm_forecast, loop2)
  message(example_site, ' temperature forecast run')
  
}
```

```{r make-standard}
# Make forecast fit the EFI standards
# Remember to change the model_id when you make changes to the model structure!
my_model_id <- 'example_ID'
my_model_id2 <- 'example_ID2'


temp_lm_forecast_EFI <- forecast_df %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter),
         variable = "temperature") %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

```

```{r write-forecast}
# Write the forecast to file
theme <- 'aquatics'
date <- temp_lm_forecast_EFI$reference_datetime[1]
forecast_name_1 <- paste0(temp_lm_forecast_EFI$model_id[1], ".csv")
forecast_file_1 <- paste(theme, date, forecast_name_1, sep = '-')
forecast_file_1


if (!dir.exists('Forecasts')) {
  dir.create('Forecasts')
}

write_csv(temp_lm_forecast_EFI, file.path('Forecasts',forecast_file_1))

neon4cast::forecast_output_validator(file.path('Forecasts',forecast_file_1))

```


```{r submit-forecast}

## # can uses the neon4cast::forecast_output_validator() to check the forecast is in the right format

# UNCOMMMENT THIS WHEN YOU ARE READY TO SUBMIT
neon4cast::submit(forecast_file = file.path('Forecasts', forecast_file_1),
                   ask = FALSE) # if ask = T (default), it will produce a pop-up box asking if you want to submit


```



```{r}
#final plot showing all of my ensemble members with all sources of uncertainty
#plots of forecasts including uncertainty
temp_lm_forecast_EFI %>% 
  filter(variable == 'temperature') %>%
  ggplot(.,aes(x=datetime, y=prediction, group = parameter)) + 
  geom_point(data = targets,aes(x=datetime, y=observation, group = 'obs'), colour = 'darkblue') +
  geom_line(alpha = 0.3, aes(colour = 'ensemble member (parameter)')) + 
  facet_wrap(~site_id, scales = 'free_y') +
  scale_x_date(expand = c(0,0), date_labels = "%d %b") +
  labs(y = 'value') +
  geom_vline(aes(linetype = 'reference_datetime', xintercept = Sys.Date()), colour = 'blue', size = 1.5) +
  labs(title = 'site_id', subtitle = 'variable = temperature', caption = 'prediction') + 
  annotate("text", x = Sys.Date() - days(10), y = 20, label = "past")  +
  annotate("text", x = Sys.Date() + days(12), y = 20, label = "future")  +
  theme_bw() +
  coord_cartesian(xlim = c(min(temp_lm_forecast$datetime) - 15,
                           Sys.Date() + 30)) +
  scale_linetype_manual(values = 'dashed', name = '') +
  scale_colour_manual(values = 'darkgrey', name = '') +
  theme(strip.text = element_text(colour = 'orange'),
        axis.title.y = element_text(colour = 'green'),
        axis.title.x = element_text(colour = 'red'),
        axis.text.y = element_text(colour = 'purple'),
        axis.text.x = element_text(colour = 'red'),
        plot.caption = element_text(hjust = 0, colour = 'purple'),
        plot.title = element_text(colour = 'orange'), 
        plot.subtitle = element_text(colour = 'green')) 
```


```{r, echo=F, warning=F}
ggplot(targets_lm, aes(x=air_temperature, y= temperature, colour = site_id)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm') +
  theme_bw() +
  facet_wrap(~site_id)
summary(fit)
```